replaced torch 2.1.1 with 2.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.2 requires torch==2.2.2, but you have torch 2.1.1 which is incompatible.
torchvision 0.17.2 requires torch==2.2.2, but you have torch 2.1.1 which is incompatible.